name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish NPM package to github
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: midi-toolkit
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout-cone-mode: 'true'
          sparse-checkout: midi-toolkit
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: midi-toolkit/.nvmrc
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
          cache-dependency-path: midi-toolkit/package-lock.json
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
