name: Release docs

on:
  push:
    branches:
      - "**"

jobs:
  generateDocs:
    name: Generate plugin docs (TypeDoc)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: midi-toolkit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout-cone-mode: 'true'
          sparse-checkout: midi-toolkit
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: midi-toolkit/.nvmrc
          registry-url: "https://npm.pkg.github.com"
          cache: "npm"
          cache-dependency-path: midi-toolkit/package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Generate docs
        run: npm run typedoc
      - name: Update pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: midi-toolkit-docs
          path: midi-toolkit/typedoc-output
          retention-days: 1
          if-no-files-found: error

  releaseDocs:
    name: Release docs to GitHub pages
    runs-on: ubuntu-latest
    needs: generateDocs
    permissions:
      id-token: write
      contents: read
      pages: write
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: midi-toolkit-docs